# Generated by Django 4.2.5 on 2023-11-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_categories_cat_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='zip_codes',
            field=models.JSONField(),
        ),
    ]
