# Generated by Django 4.2.5 on 2023-11-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_alter_areas_zip_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='zip_codes',
            field=models.TextField(),
        ),
    ]
