# Generated by Django 4.2.5 on 2023-11-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_alter_areas_zip_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(default='abc@xyz.com', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
