# Generated by Django 4.2.5 on 2023-11-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_alter_subscriptions_tier_alter_users_notify_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_email', models.EmailField(max_length=80)),
                ('guest_password', models.CharField(max_length=20)),
            ],
        ),
    ]
