# Generated by Django 4.2.5 on 2023-11-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrd',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
