# Generated by Django 4.2.5 on 2023-11-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_alter_qrd_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guests',
            new_name='GuestUsers',
        ),
    ]
