# Generated by Django 4.2.5 on 2023-12-09 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0013_alter_users_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrd',
            name='qrd_date',
            field=models.DateField(default=datetime.date(2023, 12, 9)),
        ),
    ]
