# Generated by Django 4.2.5 on 2023-12-09 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0014_qrd_qrd_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrd',
            name='qrd_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 9, 18, 7, 32, 600674, tzinfo=datetime.timezone.utc)),
        ),
    ]
