# Generated by Django 4.2.5 on 2023-12-17 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0020_alter_qrd_qrd_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrd',
            name='qrd_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
